version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "#Dani2005"
      MYSQL_DATABASE: "back_lave_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "#Dani2005"
    ports:
      - "3307:3306"
  app:
    container_name: back-lave-app
    build: .
    volumes:
      - ".:/back-projeto-lave"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: "back_lave_db"
      DB_USER: "root"
      DB_PASSWORD: "#Dani2005"
      DB_HOST: "localhost"